.TH "src/vmcli/CommandLineArgs.cs" 3 "Sun May 28 2017" "Version 0.6.2" "virtualSoC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/vmcli/CommandLineArgs.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDotArgs\&.AliasArgument\fP"
.br
.RI "\fBArgument\fP that acts as an alias for another argument\&."
.ti -1c
.RI "class \fBDotArgs\&.Argument\fP"
.br
.RI "Base class for an argument that can be registered with a \fBCommandLineArgs\fP \&. "
.ti -1c
.RI "class \fBDotArgs\&.CollectionArgument\fP"
.br
.RI "An option that can take multiple values\&."
.ti -1c
.RI "class \fBDotArgs\&.CommandLineArgs\fP"
.br
.RI "Class for defining, validating and processing command line arguments\&."
.ti -1c
.RI "class \fBDotArgs\&.FlagArgument\fP"
.br
.RI "A simple argument flag\&."
.ti -1c
.RI "class \fBDotArgs\&.OptionalOut< TResult >\fP"
.br
.RI "Helper class that offers a somewhat elegant solution for the problem of wanting to have an 'optional out' parameter for a method\&. "
.ti -1c
.RI "class \fBDotArgs\&.OptionArgument\fP"
.br
.RI "An argument that can have any value\&."
.ti -1c
.RI "class \fBDotArgs\&.SetArgument\fP"
.br
.RI "A set argument is an option that only takes values from a predefined list\&."
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBDotArgs\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for virtualSoC from the source code\&.
