.TH "DotArgs" 3 "Sun May 28 2017" "Version 0.6.2" "virtualSoC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DotArgs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAliasArgument\fP"
.br
.RI "\fBArgument\fP that acts as an alias for another argument\&."
.ti -1c
.RI "class \fBArgument\fP"
.br
.RI "Base class for an argument that can be registered with a \fBCommandLineArgs\fP \&. "
.ti -1c
.RI "class \fBCollectionArgument\fP"
.br
.RI "An option that can take multiple values\&."
.ti -1c
.RI "class \fBCommandLineArgs\fP"
.br
.RI "Class for defining, validating and processing command line arguments\&."
.ti -1c
.RI "class \fBFlagArgument\fP"
.br
.RI "A simple argument flag\&."
.ti -1c
.RI "class \fBOptionalOut\fP"
.br
.RI "Helper class that offers a somewhat elegant solution for the problem of wanting to have an 'optional out' parameter for a method\&. "
.ti -1c
.RI "class \fBOptionArgument\fP"
.br
.RI "An argument that can have any value\&."
.ti -1c
.RI "class \fBSetArgument\fP"
.br
.RI "A set argument is an option that only takes values from a predefined list\&."
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for virtualSoC from the source code\&.
