.TH "src/Komponent/Framebuffer.cs" 3 "Sun May 28 2017" "Version 0.6.2" "virtualSoC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Komponent/Framebuffer.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBVcsos\&.Komponent\&.FrameBufferInfo\fP"
.br
.ti -1c
.RI "class \fBVcsos\&.Komponent\&.Framebuffer\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBVcsos\&.Komponent\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBVcsos\&.Komponent\&.FrameBufferOrientation\fP : byte { \fBVcsos\&.Komponent\&.FrameBufferOrientation\&.Portrait\fP = 0, \fBVcsos\&.Komponent\&.FrameBufferOrientation\&.Landscape\fP = 1 }"
.br
.ti -1c
.RI "enum \fBVcsos\&.Komponent\&.FrameBufferSize\fP { \fBVcsos\&.Komponent\&.FrameBufferSize\&.VMFB_720x480x32\fP = 2, \fBVcsos\&.Komponent\&.FrameBufferSize\&.VMFB_720x240x32\fP = 4, \fBVcsos\&.Komponent\&.FrameBufferSize\&.VMFB_360x480x32\fP = 6, \fBVcsos\&.Komponent\&.FrameBufferSize\&.VMFB_800x600x32\fP = 8, \fBVcsos\&.Komponent\&.FrameBufferSize\&.VMFB_1280x720x32\fP = 10 }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "delegate void \fBVcsos\&.Komponent\&.InitFrameBuffer\fP (\fBFrameBufferInfo\fP buffer)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for virtualSoC from the source code\&.
