.TH "src/vminst/Instruction.cs" 3 "Sun May 28 2017" "Version 0.6.2" "virtualSoC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/vminst/Instruction.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBvminst\&.Instruction\fP"
.br
.RI "Basis Klasse jeder \fBInstruction\fP "
.ti -1c
.RI "class \fBvminst\&.Instructions\fP"
.br
.RI "Liste aller vorhandenen Instructionen "
.ti -1c
.RI "class \fBvminst\&.Register\fP"
.br
.RI "Item der \fBRegisters\fP Liste "
.ti -1c
.RI "class \fBvminst\&.Registers\fP"
.br
.RI "Liste aller vorhandenen \fBRegister\fP "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBvminst\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBvminst\&.InstructionParam2\fP : int { \fBvminst\&.InstructionParam2\&.Register\fP = 0, \fBvminst\&.InstructionParam2\&.Value\fP = 1, \fBvminst\&.InstructionParam2\&.Pointer\fP = 2, \fBvminst\&.InstructionParam2\&.Lable\fP = 3, \fBvminst\&.InstructionParam2\&.Variable\fP = 4, \fBvminst\&.InstructionParam2\&.No\fP = 9 }
.RI "Typ arten eines Parameter ""
.br
.ti -1c
.RI "enum \fBvminst\&.RegisterType\fP : int { \fBvminst\&.RegisterType\&.Cpu\fP = 0, \fBvminst\&.RegisterType\&.Flags\fP = 2, \fBvminst\&.RegisterType\&.Cache\fP = 3 }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for virtualSoC from the source code\&.
