.TH "Vcsos.mm.vmoperator" 3 "Sun May 28 2017" "Version 0.6.2" "virtualSoC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Vcsos.mm.vmoperator
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBVcsos\&.mm\&.vmadd\fP, \fBVcsos\&.mm\&.vmadr\fP, \fBVcsos\&.mm\&.vmand\fP, \fBVcsos\&.mm\&.vmcall\fP, \fBVcsos\&.mm\&.vmclr\fP, \fBVcsos\&.mm\&.vmdec\fP, \fBVcsos\&.mm\&.vmdiv\fP, \fBVcsos\&.mm\&.vmdvr\fP, \fBVcsos\&.mm\&.vmend\fP, \fBVcsos\&.mm\&.vmfbd\fP, \fBVcsos\&.mm\&.vmfbi\fP, \fBVcsos\&.mm\&.vminc\fP, \fBVcsos\&.mm\&.vminv\fP, \fBVcsos\&.mm\&.vmjc\fP, \fBVcsos\&.mm\&.vmjmp\fP, \fBVcsos\&.mm\&.vmjnc\fP, \fBVcsos\&.mm\&.vmjno\fP, \fBVcsos\&.mm\&.vmjo\fP, \fBVcsos\&.mm\&.vmmlr\fP, \fBVcsos\&.mm\&.vmmov\fP, \fBVcsos\&.mm\&.vmmul\fP, \fBVcsos\&.mm\&.vmnand\fP, \fBVcsos\&.mm\&.vmneg\fP, \fBVcsos\&.mm\&.vmnop\fP, \fBVcsos\&.mm\&.vmnor\fP, \fBVcsos\&.mm\&.vmor\fP, \fBVcsos\&.mm\&.vmpeek\fP, \fBVcsos\&.mm\&.vmpop\fP, \fBVcsos\&.mm\&.vmpush\fP, \fBVcsos\&.mm\&.vmret\fP, \fBVcsos\&.mm\&.vmsbr\fP, \fBVcsos\&.mm\&.vmsto\fP, \fBVcsos\&.mm\&.vmsub\fP, \fBVcsos\&.mm\&.vmunknown\fP, \fBVcsos\&.mm\&.vmvariable\fP, \fBVcsos\&.mm\&.vmxnor\fP, and \fBVcsos\&.mm\&.vmxor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBParseAndRun\fP (\fBParserFactory\fP factory)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBName\fP\fC [get]\fP"
.br
.ti -1c
.RI "string \fBInfo\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
.SH "Member Function Documentation"
.PP 
.SS "bool Vcsos\&.mm\&.vmoperator\&.ParseAndRun (\fBParserFactory\fP factory)"

.PP
Implemented in \fBVcsos\&.mm\&.vmunknown\fP, \fBVcsos\&.mm\&.vmadr\fP, \fBVcsos\&.mm\&.vmdec\fP, \fBVcsos\&.mm\&.vmdvr\fP, \fBVcsos\&.mm\&.vminc\fP, \fBVcsos\&.mm\&.vminv\fP, \fBVcsos\&.mm\&.vmjc\fP, \fBVcsos\&.mm\&.vmjnc\fP, \fBVcsos\&.mm\&.vmjno\fP, \fBVcsos\&.mm\&.vmjo\fP, \fBVcsos\&.mm\&.vmmlr\fP, \fBVcsos\&.mm\&.vmsbr\fP, \fBVcsos\&.mm\&.vmsto\fP, \fBVcsos\&.mm\&.vmadd\fP, \fBVcsos\&.mm\&.vmand\fP, \fBVcsos\&.mm\&.vmcall\fP, \fBVcsos\&.mm\&.vmclr\fP, \fBVcsos\&.mm\&.vmdiv\fP, \fBVcsos\&.mm\&.vmfbd\fP, \fBVcsos\&.mm\&.vmjmp\fP, \fBVcsos\&.mm\&.vmmov\fP, \fBVcsos\&.mm\&.vmmul\fP, \fBVcsos\&.mm\&.vmnand\fP, \fBVcsos\&.mm\&.vmneg\fP, \fBVcsos\&.mm\&.vmnor\fP, \fBVcsos\&.mm\&.vmor\fP, \fBVcsos\&.mm\&.vmpeek\fP, \fBVcsos\&.mm\&.vmpop\fP, \fBVcsos\&.mm\&.vmpush\fP, \fBVcsos\&.mm\&.vmret\fP, \fBVcsos\&.mm\&.vmsub\fP, \fBVcsos\&.mm\&.vmxnor\fP, \fBVcsos\&.mm\&.vmxor\fP, \fBVcsos\&.mm\&.vmend\fP, \fBVcsos\&.mm\&.vmfbi\fP, \fBVcsos\&.mm\&.vmnop\fP, and \fBVcsos\&.mm\&.vmvariable\fP\&.
.SH "Property Documentation"
.PP 
.SS "string Vcsos\&.mm\&.vmoperator\&.Info\fC [get]\fP"

.SS "string Vcsos\&.mm\&.vmoperator\&.Name\fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for virtualSoC from the source code\&.
