.TH "Vcsos.VMExections" 3 "Sun May 28 2017" "Version 0.6.2" "virtualSoC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Vcsos.VMExections
.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBErrorCode\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBVMExecptionType\fP \fBType\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
.SH "Property Documentation"
.PP 
.SS "int Vcsos\&.VMExections\&.ErrorCode\fC [get]\fP, \fC [set]\fP"

.SS "\fBVMExecptionType\fP Vcsos\&.VMExections\&.Type\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for virtualSoC from the source code\&.
