.TH "Vcsos.NamedTimer" 3 "Sun May 28 2017" "Version 0.6.2" "virtualSoC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Vcsos.NamedTimer
.SH SYNOPSIS
.br
.PP
.PP
Inherits Timer\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNamedTimer\fP (double interval, int id)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBID\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Vcsos\&.NamedTimer\&.NamedTimer (double interval, int id)"

.PP
.nf
44 : base(interval) { ID = id; }
.fi
.SH "Property Documentation"
.PP 
.SS "int Vcsos\&.NamedTimer\&.ID\fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for virtualSoC from the source code\&.
