.TH "Vcsos.Komponent.IVMKomponente" 3 "Sun May 28 2017" "Version 0.6.2" "virtualSoC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Vcsos.Komponent.IVMKomponente
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBVcsos\&.Komponent\&.Memory\fP, and \fBVcsos\&.Komponent\&.vmKomponente\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBName\fP\fC [get]\fP"
.br
.ti -1c
.RI "string \fBAuthor\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
.SH "Property Documentation"
.PP 
.SS "string Vcsos\&.Komponent\&.IVMKomponente\&.Author\fC [get]\fP"

.SS "string Vcsos\&.Komponent\&.IVMKomponente\&.Name\fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for virtualSoC from the source code\&.
