.TH "vmasm.InstructionNotFoundException" 3 "Sun May 28 2017" "Version 0.6.2" "virtualSoC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vmasm.InstructionNotFoundException
.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInstructionNotFoundException\fP (string inst)"
.br
.in -1c
.SH "Detailed Description"
.PP 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "vmasm\&.InstructionNotFoundException\&.InstructionNotFoundException (string inst)"

.PP
.nf
29             : base("Instruction " + inst + " don't excist")
30         {
31         }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for virtualSoC from the source code\&.
