.TH "vmcli.IInputType" 3 "Sun May 28 2017" "Version 0.6.2" "virtualSoC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vmcli.IInputType
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBvmcli\&.GzipInputType\fP, and \fBvmcli\&.RawInputType\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "byte [] \fBLoadFromStream\fP (System\&.IO\&.Stream stream)"
.br
.ti -1c
.RI "byte [] \fBLoadFromFile\fP (string path)"
.br
.in -1c
.SH "Detailed Description"
.PP 
.SH "Member Function Documentation"
.PP 
.SS "byte [] vmcli\&.IInputType\&.LoadFromFile (string path)"

.PP
Implemented in \fBvmcli\&.RawInputType\fP, and \fBvmcli\&.GzipInputType\fP\&.
.SS "byte [] vmcli\&.IInputType\&.LoadFromStream (System\&.IO\&.Stream stream)"

.PP
Implemented in \fBvmcli\&.GzipInputType\fP, and \fBvmcli\&.RawInputType\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for virtualSoC from the source code\&.
