.TH "vminst.Register" 3 "Sun May 28 2017" "Version 0.6.2" "virtualSoC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vminst.Register \- Item der \fBRegisters\fP Liste  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRegister\fP (string n, int t)"
.br
.RI "Konstructor für ein \fBRegister\fP "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBName\fP"
.br
.RI "Name des \fBRegisters\fP "
.ti -1c
.RI "\fBRegisterType\fP \fBType\fP"
.br
.RI "Typ des \fBRegisters\fP "
.in -1c
.SH "Detailed Description"
.PP 
Item der \fBRegisters\fP Liste 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "vminst\&.Register\&.Register (string n, int t)"

.PP
Konstructor für ein \fBRegister\fP 
.PP
\fBParameters:\fP
.RS 4
\fIn\fP Name des \fBRegisters\fP
.br
\fIt\fP Typ des \fBRegisters\fP
.RE
.PP

.PP
.nf
177 { Name = n; Type = (RegisterType)t; }
.fi
.SH "Member Data Documentation"
.PP 
.SS "string vminst\&.Register\&.Name"

.PP
Name des \fBRegisters\fP 
.SS "\fBRegisterType\fP vminst\&.Register\&.Type"

.PP
Typ des \fBRegisters\fP 

.SH "Author"
.PP 
Generated automatically by Doxygen for virtualSoC from the source code\&.
